### PR TITLE
Publish manifest files, helm chart and kubectl-kadalu files to gh-pages

### PR DESCRIPTION
**Pull request by aravindavk**
Once published to `gh-pages` branch of this repo, those files will be
available as `https://kadalu.io/kadalu/downloads/<file-name>`

For example, https://kadalu.io/kadalu/downloads/kubectl-kadalu

Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.io>

### CODE REVIEW

**Comment by aravindavk** [comment]
Not yet sure if it retains the files across the steps to upload the files. @amarts any suggestions on testing that?

**Comment by leelavg** [comment]
@aravindavk No, the artefacts will not be retained between jobs,
- Each call to `runs-on: ubuntu-latest` uses a new instance
- I was using `outputs` construct to store any strings
Need to figure out a way for persistent store across jobs.

**Comment by leelavg** [comment]
A quick search resulted in below official actions can be used, we can give a try:
- [Upload Artifact](https://github.com/actions/upload-artifact)
- [Download Artifact](https://github.com/actions/download-artifact)

**Comment by aravindavk** [comment]
Thanks @leelavg. I combined helm chart publish step with previous job and added gh-pages step to the same job.

**Pull request merged**
