### PR TITLE
Change builder base image to `python:3.10-bullseye`

### PR DESCRIPTION
**Pull request by aravindavk**
Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.io>

### CODE REVIEW

**Comment by leelavg** [comment]
- Uh oh, this isn't good.
- Maybe base image change resulted in regression 🤔

**Comment by aravindavk** [comment]
Reverted the upgrade PR to see if that is the issue. We need to upgrade the container images to remove the issues reported by `docker scan`

**Comment by leelavg** [comment]
@aravindavk found the issue, 
1. remove all changes in this pr and then
2. change `debian:bullseye` to `python:3.10-bullseye` in the base image?

- all packages are being installed in `/kadalu/lib/python3.9/site-packages` and we are installing `python3.10` in component images
- so the components are failing to access the packages
- didn't test the change locally as this seems to be straightforward.

**Comment by aravindavk** [comment]
> @aravindavk found the issue,
> 
>     1. remove all changes in this pr and then
> 
>     2. change `debian:bullseye` to `python:3.10-bullseye` in the base image?
> 
> 
>     * all packages are being installed in `/kadalu/lib/python3.9/site-packages` and we are installing `python3.10` in component images
> 
>     * so the components are failing to access the packages
> 
>     * didn't test the change locally as this seems to be straightforward.

Just triggered the build by changing the base images of Server, Operator and CSI as below.

```diff
-FROM python:3.9.6-slim-bullseye as prod
+FROM debian:bullseye-slim as prod
```
I will try your suggestion once the CI completes with this change.

**Comment by aravindavk** [comment]
@leelavg Fixed now with your suggestion. Merge this if looks good.

**Comment by leelavg** [comment]
> @leelavg Fixed now with your suggestion. Merge this if looks good.

- Ack, if you have sometime could you pls sanitize the base dockerfile as well? Like removing installation of python again, etc
- Not urgent as of now however those changes will be good

**Comment by aravindavk** [comment]
> > @leelavg Fixed now with your suggestion. Merge this if looks good.
> 
>     * Ack, if you have sometime could you pls sanitize the base dockerfile as well? Like removing installation of python again, etc
> 
>     * Not urgent as of now however those changes will be good

Done.

**Review by leelavg — APPROVED** [review]

**Pull request merged**
