### PR TITLE
Upgrade all components python deps

### PR DESCRIPTION
**Pull request by leelavg**
Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

**Comment by leelavg** [comment]
- Before working on using grpc whl files in release, want to bump up all deps and see CI is working with latest modules.

**Comment by leelavg** [comment]
- we are stuck with `kubernetes==11.0.0` and we'll be using that for a foreseeable future due to https://github.com/kubernetes-client/python/issues/1333

**Comment by leelavg** [comment]
- local testing is working for me, will take a look at CI when it's possible

**Review by amarts — APPROVED** [review]

**Comment by amarts** [comment]
@aravindavk just want to you to keep in mind all these changes done in `devel` branch with `moana` branch.

**Pull request merged**
