### PR TITLE
fix find command in quota-crawler script

### PR DESCRIPTION
**Pull request by leelavg**
Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

**Comment by leelavg** [comment]
- i tested this earlier but somehow slipped from #828

**Review by sac — APPROVED** [review]
@leelavg looks good to me. Just curious why do you need -printf '.' ?
I mean why not just:
```dirs=$(find $MOUNT_DIR/*/subvol -mindepth 1 -maxdepth 1 -type d 2>/dev/null| wc -l);```

**Comment by leelavg** [comment]
@sac thanks for the review,
- that'd also work, I just want the count not the paths/files, so it'll just print dot `.` for each find and `wc -c` count chars
- micro optimisation 😅

**Comment by leelavg** [comment]
- there might be relatively more chances that users may deploy kadalu during weekends for evaluation, so merging this PR.

**Pull request merged**
