### PR TITLE
Enhance existing python2 cli-support 

### PR DESCRIPTION
**Pull request by vatsa287**
- Added 'from __future__ import print_function to utils.py
  Was throwing error when compiled in python2 for all files which imported utils.py.

- Improved pylint in kubectl_kadalu

Signed-off-by: Shree Vatsa N <vatsa@kadalu.io>

### CODE REVIEW

**Comment by vatsa287** [comment]
```bash
vatsa@vatsa-VirtualBox:~/kadalu/cli/kubectl_kadalu$ pylint storage_list.py 
No config file found, using default configuration
************* Module storage_list
C: 12, 0: Old-style class defined. (old-style-class)
C: 24, 0: Old-style class defined. (old-style-class)
C:149, 7: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
E:221,15: Undefined variable 'FileNotFoundError' (undefined-variable)
E:244,11: Undefined variable 'FileNotFoundError' (undefined-variable)-----------------------------------
Your code has been rated at 9.13/10vatsa@vatsa-VirtualBox:~/kadalu/cli/kubectl_kadalu$ pylint3 storage_list.py 
No config file found, using default configuration
************* Module storage_list
C:149, 7: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)------------------------------------------------------------------
Your code has been rated at 9.93/10 (previous run: 9.13/10, +0.81)
```

**Comment by vatsa287** [comment]
```bash
vatsa@vatsa-VirtualBox:~/kadalu/cli/kubectl_kadalu$ python2 install.py 
Traceback (most recent call last):
  File "install.py", line 8, in <module>
    import utils
  File "/home/vatsa/kadalu/cli/kubectl_kadalu/utils.py", line 59
    print("Error while running the following command", file=sys.stderr)
                                                           ^
SyntaxError: invalid syntax
vatsa@vatsa-VirtualBox:~/kadalu/cli/kubectl_kadalu$ python3 install.py 
vatsa@vatsa-VirtualBox:~/kadalu/cli/kubectl_kadalu$ python2 storage_list.py 
Traceback (most recent call last):
  File "storage_list.py", line 8, in <module>
    import utils
  File "/home/vatsa/kadalu/cli/kubectl_kadalu/utils.py", line 59
    print("Error while running the following command", file=sys.stderr)
                                                           ^
SyntaxError: invalid syntax
vatsa@vatsa-VirtualBox:~/kadalu/cli/kubectl_kadalu$ python3 storage_list.py
```

**Comment by amarts** [comment]
Do we need support for python2? I guess we can clearly say we only support python3. That is totally fine IMO.

**Review by amarts — COMMENTED** [review]
LGTM

**Review by aravindavk — APPROVED** [review]

**Pull request merged**
