### PR TITLE
Support custom kubelet dir and optimize helm chart struct

### PR DESCRIPTION
**Pull request by iutx**
**What this PR does / why we need it**:
1. support custom kubelet dir
2. optimize helm chart struct, add common charts for some standard template. This will facilitate standardization and subsequent extension.
3. To be compatible with existing yaml struct, it hasn't changed much.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:
1. Why move kubernetesDistro from operator and csi-nodeplugin?
Values `kubeletDir` and `kubernetesDistro` used as the same parameter in general better, I think it's generic.
2. Why add common chart?
Common charts can provider standard template, like version,labels and more. For compatible with existing yaml struct, some of the content is not abstract. RBAC and ServiceAccount will also be needed in the future.
3. Something todo
The values of helm install command will change to
```shell
--set operator.enabled=true --set global.kubernetesDistro=$K8S_DIST [e.g. --set global.kubeletDir=/data/kubelet]
--set csi-nodeplugin.enabled=true --set global.kubernetesDistro=$K8S_DIST [e.g. --set global.kubeletDir=/data/kubelet]
```

thanks for reading.

**Checklist**
- [x] Documentation added
- [x] Tests updated
- [x] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by leelavg** [comment]
- Seems we need to work on https://github.com/kadalu/kadalu/issues/850 at the earliest as it's creating confusion to new contributions 
- @aravindavk I think best way is as you mentioned, we'll replace `gen-manifest` in Makefile with `helm template`

@iutx thanks for the PR, give us sometime to sort these things.

**Comment by leelavg** [comment]
- pls rebase and needs a partial re-work on this pr, thanks for the patience.

**Comment by iutx** [comment]
> * pls rebase and needs a partial re-work on this pr, thanks for the patience.

It's great, i will re-work for this pr as soon as possible.

**Comment by leelavg** [comment]
@iutx could you pls sign your commit and I'll trigger CI?

**Comment by iutx** [comment]
`/helm/kadalu/charts/csi-nodeplugin/templates/namespace.yaml`
`/helm/kadalu/charts/operator/templates/namespace.yaml`

namespace in charts template will cause errors when execute upgrade.
```shell
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Namespace "kadalu" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi-nodeplugin"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kadalu"
```

Adding namespace resources via template looks bad, perhaps there is a better way to add labels to namespace for OpenShit, such as hook Jobs

**Comment by iutx** [comment]
> @iutx could you pls sign your commit and I'll trigger CI?

Sorry, it has been added

**Comment by leelavg** [comment]
> `/helm/kadalu/charts/csi-nodeplugin/templates/namespace.yaml` `/helm/kadalu/charts/operator/templates/namespace.yaml`
> 
> namespace in charts template will cause errors when execute upgrade.
> 
> ```shell
> Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Namespace "kadalu" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi-nodeplugin"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kadalu"
> ```
> 
> Adding namespace resources via template looks bad, perhaps there is a better way to add labels to namespace for OpenShit, such as hook Jobs

- We are open to contribution here as initially we were creating manifests in a different and recently move to helm fully
- However namespace thing was the only one which I wasn't confident about and so just went with what's working now
- Seeing that upgrade might fail, need to invest some time to get around it, thanks for the report

**Comment by iutx** [comment]
> > `/helm/kadalu/charts/csi-nodeplugin/templates/namespace.yaml` `/helm/kadalu/charts/operator/templates/namespace.yaml`
> > namespace in charts template will cause errors when execute upgrade.
> > ```shell
> > Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Namespace "kadalu" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi-nodeplugin"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kadalu"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Adding namespace resources via template looks bad, perhaps there is a better way to add labels to namespace for OpenShit, such as hook Jobs
> 
> * We are open to contribution here as initially we were creating manifests in a different and recently move to helm fully
> * However namespace thing was the only one which I wasn't confident about and so just went with what's working now
> * Seeing that upgrade might fail, need to invest some time to get around it, thanks for the report

Problem about namespace when upgrade, use install and upgrade hook for namespace maybe solution it.
I will testing it later. If can solute this problem, i will create new pr to discuss together.

**Review by leelavg — APPROVED** [review]
thanks for the PR!

**Pull request merged**
