### PR TITLE
[Nomad] Support for external gluster cluster in Nomad via Kadalu CSI

### LINKED ISSUE #510: Please write documentation for use with Nomad.
[Nomad](https://www.hashicorp.com/products/nomad) is a simpler alternative to Kubernetes and [works with CSI plugins](https://www.nomadproject.io/docs/internals/plugins/csi).

### PR DESCRIPTION
**Pull request by leelavg**
- Use Kadalu CSI as a bridge b/n external gluster cluster
and Nomad jobs which requires persistent data

Fixes: #510

Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

**Comment by leelavg** [comment]
Enhancements based on request:
- Deploy and manage internal gluster cluster by Nomad (feature parity wrt k8s)
- Use nomad ACLs, namespaces and consul integration for dynamic config (~kadalu-info)
- Combing above logic in nomad specific operator
- Factor out existing operator/main.py methods as many can be re-used

PS: Repeating again, will be taking up above only if there're at-least ~10 requests

**Comment by leelavg** [comment]
@aravindavk not expecting any more updates to this branch, pls take a look when you get time.

Referenced issue may stay for longer time but we aren't dependent on that anyways. 

Not totally related to this PR, we need a good, tested doc for upgrade.

**Comment by aravindavk** [comment]
> @aravindavk not expecting any more updates to this branch, pls take a look when you get time.
> 
> Referenced issue may stay for longer time but we aren't dependent on that anyways.
> 
> Not totally related to this PR, we need a good, tested doc for upgrade.

This is awesome. Thanks. I will review by this week.

**Comment by amarts** [comment]
As it is a 'tested' documentation, and considering it won't break any code, merging.

**Pull request merged**
