### PR TITLE
operator/Dockerfile: download the architecture specific kubectl

### LINKED ISSUE #264: failed deployment on arm64 architecture
I am trying to install kadalu on my k8s cluster running in arm64 infrastructure. I followed your instructions and I ran the command 
```
kubectl apply -f kadalu-operator-master.yml
```
The operator container went up properly,
```
$ kubectl get pods -n kadalu -o wide
NAMESPACE     NAME                                          READY     STATUS    RESTARTS   AGE       IP               NODE                    NOMINATED NODE   READINESS GATES
kadalu        operator-79ffc9f8db-ntl4g                     1/1       Running   0          4h55m     10.244.3.2       worker03   <none>           <none>
```
but the deployment stopped at this stage.
doing some investigation in operator container it seems the kubectl command fails due to wrong architecture. 
```
[root@d33037d08fc1 /]# kubectl 
bash: /usr/bin/kubectl: cannot execute binary file: Exec format error
```
from Kadulu/operator/Dockerfile in master branch there is the wrong package download
```
# Always have the latest stable kubectl
RUN curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl -o /usr/bin/kubectl
```
Maybe you need to modify the url depending on the architecture
```
RUN curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/${ARCH}/kubectl -o /usr/bin/kubectl``
```

### PR DESCRIPTION
**Pull request by amarts**
Fixes: #264
Signed-off-by: Amar Tumballi <amar@kadalu.io>

### CODE REVIEW

**Review by aravindavk — APPROVED** [review]

**Comment by amarts** [comment]
Failure is due to below:
```

kubectl info: exec: fork/exec /usr/local/bin/kubectl: exec format error
/usr/local/bin/kubectl: line 1: syntax error near unexpected token `<'
/usr/local/bin/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.15.0/bin/linux/x86_64/kubectl</Details></Error>'
```

**Comment by aravindavk** [comment]
I think `amd64` in case arch is `x86_64`

**Comment by iamenr0s** [comment]
It's correct. the same for arm64 architecture.
`ARCH=uname -m | sed 's|aarch64|arm64|' | sed 's|x86_64|amd64|'`

**Comment by amarts** [comment]
Thanks @enr0s :+1:

Working fine on latest version!

**Pull request merged**
