### PR TITLE
kadalu-sample-setup

### PR DESCRIPTION
**Pull request by vatsa287**
Script with cli for faster sample setup of Kadalu.
- Will take sample yaml files from /examples dir with desired configurations.
- --storage-value and --device-file-path are mandatory options.

Referenced from issue: #326

Signed-off-by: Shree Vatsa N <vatsa@kadalu.io>

### CODE REVIEW

**Comment by vatsa287** [comment]
## TEST RUN

vatsa@vatsa-VirtualBox:~/kadalu/extras/scripts$ sudo ./kadalu-sample-setup.sh --device-file-path=/mnt/disk1 --storage-value=100Mi
namespace/kadalu unchanged
serviceaccount/kadalu-operator unchanged
serviceaccount/kadalu-csi-nodeplugin unchanged
serviceaccount/kadalu-csi-provisioner unchanged
serviceaccount/kadalu-server-sa unchanged
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage unchanged
clusterrole.rbac.authorization.k8s.io/kadalu-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator unchanged
deployment.apps/operator unchanged
minikube
Number of hostname is 1
Hostname is minikube
kadalustorage.kadalu-operator.storage/storage-pool-1 unchanged
persistentvolumeclaim/pv1 created
pod/pod1 created
15: Waiting for pods to come up...
30: Waiting for pods to come up...
45: Waiting for pods to come up...
60: Waiting for pods to come up...
75: Waiting for pods to come up...
90: Waiting for pods to come up...
105: Waiting for pods to come up...
120: Waiting for pods to come up...
135: Waiting for pods to come up...
150: Waiting for pods to come up...
165: Waiting for pods to come up...
180: Waiting for pods to come up...
195: Waiting for pods to come up...
NAME   READY   STATUS      RESTARTS   AGE     IP            NODE       NOMINATED NODE   READINESS GATES
pod1   0/1     Completed   0          8m22s   172.17.0.10   minikube   <none>           <none>

vatsa@vatsa-VirtualBox:~$ sudo kubectl get pvc
[sudo] password for vatsa: 
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
pv1    Bound    pvc-f1be2a10-7ba6-4693-9f0e-180abf7fecbd   100Mi      RWO            kadalu.replica1   6m42s

vatsa@vatsa-VirtualBox:~$ sudo kubectl get pods
NAME   READY   STATUS      RESTARTS   AGE
pod1   0/1     Completed   0          6m48s

**Comment by vatsa287** [comment]
## UPDATED TEST RUN

vatsa@vatsa-VirtualBox:~/kadalu/extras/scripts$ sudo ./kadalu-sample-setup.sh --storage-value=100Mi --device-file-path=/mnt/disk1 -s sp2
namespace/kadalu created
serviceaccount/kadalu-operator created
serviceaccount/kadalu-csi-nodeplugin created
serviceaccount/kadalu-csi-provisioner created
serviceaccount/kadalu-server-sa created
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage unchanged
clusterrole.rbac.authorization.k8s.io/kadalu-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator unchanged
deployment.apps/operator created
minikube
Number of hostname is 1
Hostname is minikube
kadalustorage.kadalu-operator.storage/sp2 unchanged
persistentvolumeclaim/pv1 created
pod/pod1 created
15: Waiting for pods to come up...
All Kadalu pods in status: 'Running'
PVC pv1 in status: 'Bound'
PVC pod1 in status: 'Completed'
Successful after 24 seconds

vatsa@vatsa-VirtualBox:/tmp$ sudo kubectl get pods -nkadalu
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-hv856   3/3     Running   0          66s
kadalu-csi-provisioner-0      4/4     Running   0          66s
operator-59f656cf56-lsl64     1/1     Running   0          75s
server-sp2-0-0                2/2     Running   0          53s

vatsa@vatsa-VirtualBox:/tmp$ sudo kubectl get pvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
pv1    Bound    pvc-1e794f04-6a36-41ba-9d83-1c535c45f8fc   100Mi      RWO            kadalu.replica1   49s

vatsa@vatsa-VirtualBox:/tmp$ sudo kubectl get pod
NAME   READY   STATUS              RESTARTS   AGE
pod1   0/1     ContainerCreating   0          57s

**Review by amarts — COMMENTED** [review]
LGTM as a sample example script... can be optimized further i guess, but no harm to get in like this too.

**Review by amarts — APPROVED** [review]
Lets improve it based on feedback.

**Pull request merged**
