### PR TITLE
Use buildx while building local images

### PR DESCRIPTION
**Pull request by leelavg**
- Use buildx for building local images to simulate release scripts
- Break python instructions onto separate line from builder dockerfile
- Copy only requirements files while building local images

Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

**Comment by leelavg** [comment]
- Not sure why we aren't using buildx from start, either it was experimental when project started or some other reason that I'm not aware of
- Please comment if there are reservations against using buildx by default
- We can go a step further and build multiarch (atleast arm64?) for only component images with buildx (<5min) and just run image with docker just to verify no dependency issues?

**Comment by amarts** [comment]
* We didn't use buildx from start as in July 2019 it was not yet stable.
* Good to use it IMO
* I believe its not easy to run a different arch image ? How do you intend to test in CI/CD ?

**Review by amarts — APPROVED** [review]
LGTM

**Review by aravindavk — APPROVED** [review]

**Comment by leelavg** [comment]
> I believe its not easy to run a different arch image ? How do you intend to test in CI/CD ?

well it's a long shot, here's what I'm thinking:
1. Use [setup-qemu-action](https://github.com/docker/setup-qemu-action) in every pr flow (<10s)
2. Edit `build.sh` to build (via buildx) arm64 variant of only component images (we'll pull/cache builder arm instance)
3. After amd64 tests complete, we'll run component images via docker (exact sha256 of an image can be used with docker to run arm images) just to see that the monitor process is starting in all images or not
4. When we are uncertain whether whole arm build is needed to verify a breaking change, we manipulate via commit message to build all containers

however this is not an easy task and as we are almost there unifying arm and amd images I intend to implement above in worst case.

Best way is, with this PR we are using buildx, before a release we'll use AWS machine to build containers and perform some sanity checks.

**Pull request merged**
