### PR TITLE
Update manifest files 

### PR DESCRIPTION
**Pull request by vatsa287**
Update manifest files with missing tolerations values from #733.

Signed-off-by: Shree Vatsa N <vatsa@kadalu.io>

### CODE REVIEW

**Comment by leelavg** [comment]
- i did mention to make change either in annotation or in fastapi
- however, i still feel making the change in fast api is better, rationale being, standard path is /metrics.
- what do you say?

**Comment by vatsa287** [comment]
Sure will change API endpoint to /metrics/

**Comment by leelavg** [comment]
> Sure will change API endpoint to /metrics/
- i presume it's `/metrics/` to `/metrics`

**Comment by vatsa287** [comment]
The metrics when accessed by a service seems to be working fine, so dropping those changes until reported again. Adding only files by missed operation `make gen-manifest`

**Review by leelavg — APPROVED** [review]
/lgtm

**Review by amarts — APPROVED** [review]

**Pull request merged**
