### PR TITLE
Quotad: Fix for 64-bit inode XFS

### PR DESCRIPTION
**Pull request by Joibel**
kadala-quotad uses inode numbers as project numbers when setting up
quotas on XFS. Project numbers are always 32bit values, but when using
large disks XFS will generate 64 bit inode numbers.

This change modulos the inode number by 2^32 to get the inode number
in the correct range for project numbers. It does nothing good if this
results in a clash with another project number. As this seems to be
quite unlikely it feels good enough.

### CODE REVIEW

**Comment by aravindavk** [comment]
Interesting find. One possible issue with this approach is that if two dirs with inode numbers `32330318` and `4327297614` will get the same project ID.

**Comment by Joibel** [comment]
Yes, this is definitly a risk, although unlikely with the relatively small number of volumes per brick relative to the 2^32 possible projects. I haven't looked into how XFS allocates inode numbers, so perhaps that increases the risk.

Alternatives would rely on much more complex code detecting collisions and then mitigating them in a consistent and predictable way (remembering that the item you may have been colliding with in the past may have gone away), persisting data in some way, or generating project numbers in a completely diffferent way.

My preference would be to add a project number to the per-subvol .json file, and get the operator to allocate them, as it's the one with all the information and access to all the state. This is obviously a compatibility breaking and much more involved change.

**Comment by amarts** [comment]
This fix is good :+1: 

In any case, ideal fix for us as project is to get glusterfs natively supporting quota, so we can use distribute. In which case, complete storage array can be a single glusterfs volume. Trying that with glusterfs quota.

This is required till that gets into glusterfs.

**Review by amarts — APPROVED** [review]

**Comment by amarts** [comment]
@aravindavk feel free to merge when you have a look on this again.

**Review by aravindavk — APPROVED** [review]

**Pull request merged**
