### PR TITLE
Doc: Fix user guide title

### PR DESCRIPTION
**Pull request by johalaoui**
**What this PR does / why we need it**:
Fixes a user guide title. I hope this fixes the index of the documentation website.
Currently it shows [Mounted Block Volume](https://kadalu.github.io/docs/k8s-storage/devel/mounted-block-volume/) instead of [Block Volume](https://kadalu.github.io/docs/k8s-storage/devel/block-volume/).

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Review by leelavg — APPROVED** [review]
- thanks for finding the issue and sending a fix!

**Comment by leelavg** [comment]
@aravindavk need a quick merge and docs rebuild. Or the docs will rebuild automatically?

**Comment by johalaoui** [comment]
Thanks to both of you. The title on the documentation webpage still needs to be corrected.

**Comment by aravindavk** [comment]
Fixed now: https://kadalu.github.io/docs/k8s-storage/devel/block-volume/

**Pull request merged**
