### PR TITLE
Thin arbiter

### LINKED ISSUE #37: RFE: thin-arbiter (metro cluster) support
GlusterFS-7 is releasing with thin-arbiter support. Once released, if kadalu supports thin-arbiter cluster support, it will help many users who have only 2 data centers.

### PR DESCRIPTION
**Pull request by amarts**
Supported the thin-arbiter volume type as per the RFC specified @

https://kadalu.io/rfcs/0003-kadalu-thin-arbiter-support

Provided option to take default tie-breaker node if no tie-breaker is provided.

Fixes: #37

### CODE REVIEW

**Comment by amarts** [comment]
Found a crash of glusterfs

```
[2020-01-29 06:12:48.697763] I [fuse-bridge.c:5162:fuse_init] 0-glusterfs-fuse: FUSE inited with protocol versions: glusterfs 7.24 kernel 7.26
[2020-01-29 06:12:48.697777] I [fuse-bridge.c:5777:fuse_graph_sync] 0-fuse: switched to graph 0
pending frames:
frame : type(1) op(NULL)
patchset: git://git.gluster.org/glusterfs.git
signal received: 11
time of crash: 
2020-01-29 06:12:48
configuration details:
argp 1
backtrace 1
dlfcn 1
libpthread 1
llistxattr 1
setfsid 1
spinlock 1
epoll.h 1
xattr.h 1
st_atim.tv_nsec 1
package-string: glusterfs 7.2
/lib64/libglusterfs.so.0(+0x2ac34)[0x7f6e337c0c34]
/lib64/libglusterfs.so.0(gf_print_trace+0x333)[0x7f6e337cb8f3]
/lib64/libc.so.6(+0x37ec0)[0x7f6e3354fec0]
/usr/lib64/glusterfs/7.2/xlator/features/utime.so(+0x30e1)[0x7f6e2f02b0e1]
/usr/lib64/glusterfs/7.2/xlator/performance/nl-cache.so(+0x338b)[0x7f6e2f01938b]
/usr/lib64/glusterfs/7.2/xlator/debug/io-stats.so(+0x65b2)[0x7f6e2efe65b2]
/lib64/libglusterfs.so.0(default_lookup+0xbf)[0x7f6e3385790f]
/usr/lib64/glusterfs/7.2/xlator/meta.so(+0x41fd)[0x7f6e2efcd1fd]
/lib64/libglusterfs.so.0(default_lookup+0xbf)[0x7f6e3385790f]
/usr/lib64/glusterfs/7.2/xlator/meta.so(+0x41fd)[0x7f6e2efcd1fd]
/lib64/libglusterfs.so.0(syncop_lookup+0x2a3)[0x7f6e33801ac3]
/usr/lib64/glusterfs/7.2/xlator/mount/fuse.so(+0x22243)[0x7f6e32191243]
/usr/lib64/glusterfs/7.2/xlator/mount/fuse.so(+0x237a9)[0x7f6e321927a9]
/usr/lib64/glusterfs/7.2/xlator/mount/fuse.so(+0x23c48)[0x7f6e32192c48]
/lib64/libpthread.so.0(+0x84c0)[0x7f6e336e84c0]
/lib64/libc.so.6(clone+0x43)[0x7f6e33614163]
---------
```

**Comment by aravindavk** [comment]
@amarts are you planning to add Tiebreaker support for `kubectl kadalu storage-add`?

**Comment by amarts** [comment]
The crash above got resolved when I used the same Replica3 template for volfile (i had optimized earlier). Now found one more failure..

```
  File "/kadalu/server.py", line 30, in <module>
    start_server_process()
  File "/kadalu/server.py", line 23, in start_server_process
    shd.start()
  File "/kadalu/shd.py", line 37, in start
    generate_shd_volfile(volfile_path, volname)
  File "/kadalu/shd.py", line 27, in generate_shd_volfile
    Template(content).stream(**data).dump(client_volfile)
  File "/usr/local/lib64/python3.7/site-packages/jinja2/environment.py", line 1313, in dump
    fp.writelines(iterable)
  File "/usr/local/lib64/python3.7/site-packages/jinja2/environment.py", line 1309, in <genexpr>
    iterable = (x.encode(encoding, errors) for x in self)
  File "/usr/local/lib64/python3.7/site-packages/jinja2/environment.py", line 1357, in __next__
    return self._next()
  File "/usr/local/lib64/python3.7/site-packages/jinja2/environment.py", line 1125, in generate
    yield self.environment.handle_exception()
  File "/usr/local/lib64/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib64/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 75, in top-level template code
  File "/usr/local/lib64/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 2
```

Looks like I missed some bricks[2] element.

**Comment by aravindavk** [comment]
Shd template name is hard coded here https://github.com/kadalu/kadalu/blob/master/server/shd.py#L22

**Comment by amarts** [comment]
@aravindavk thanks for pointing the hardcoded value. Fixed now.

> @amarts are you planning to add Tiebreaker support for kubectl kadalu storage-add?

Not in v0.5, may be v0.6 or v0.7 once there are confirmation that it works from the field. I will open an issue, would be good for external contributors to pick it up too.

**Comment by aravindavk** [comment]
> Not in v0.5, may be v0.6 or v0.7 once there are confirmation that it works from the field. I will open an issue, would be good for external contributors to pick it up too.

Doc changed recently mentioning CLI usage everywhere. This may add confusion if we are documenting this in v0.5

**Comment by amarts** [comment]
Got it!

Lets not document it in v0.5 (or add a tech preview mention). We can add it as a separate kubectl_kadalu package release once we have the support. Thats my take.

**Comment by amarts** [comment]
Or, not merge this in v0.5 itself, and make it available as a nightly, or master tag.

**Comment by amarts** [comment]
This patch is ready to be reviewed :-)

@aravindavk @itisravi @sac

**Review by aravindavk — APPROVED** [review]
Looks good to me. We may have to add a document to run the Tie breaker node. (If tie-breaker.kadalu.io is not used)

**Comment by amarts** [comment]
I was thinking of pointing them to gluster documentation.

**Comment by amarts** [comment]
Simple idea. Should we build a simple image for gluster users? who can deploy it using `docker run` ? We can provide the Dockerfile, and volfile template of thin-arbiter? That is the what thin-arbiter setup does. This way, no confusion for anyone to deploy, and they can choose any system to put tie-breaker.

**Pull request merged**
