### PR TITLE
doc(upgrade): Updates for k8s/k3s

### PR DESCRIPTION
**Pull request by vherrlein**
Changes:
- URLs pointing to the latest releases
- Generic comment on server types

### CODE REVIEW

**Comment by leelavg** [comment]
- IMHO, it's better not to mention specific k8s distribution as we support rke, microk8s and okd as well and upgrade isn't any different for those 😉 
- Edit to the links lgtm, if possible can you pls sign your commit?

**Comment by vherrlein** [comment]
For the upgrade process, do we need to specify the right operator file ?
From my understanding it was the followin:
- Generic Kubernetes: kadalu-operator.yaml
- MicroK8s: kadalu-operator-microk8s.yaml
- RKE: kadalu-operator-rke.yaml
- OpenShift: kadalu-operator-openshift.yaml

For signing it, I must go back on my laptop.
I'll do it when I come back this evening.

**Comment by leelavg** [comment]
- You are correct, maybe keep the edits as it is and add a line at the top like, 'please use corresponding yaml files based on your k8s distribution' if you are fine with that.

**Comment by vherrlein** [comment]
sure

**Comment by vherrlein** [comment]
As requested, changes have been applied.

Regards.

**Review by leelavg — APPROVED** [review]
Thanks a lot for the revision, lgtm.

**Pull request merged**
