### PR TITLE
doc: Fix kubectl-kadalu version

### PR DESCRIPTION
**Pull request by aravindavk**
Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.io>

### CODE REVIEW

**Comment by amarts** [comment]
This is one thing I wanted to syncup with you. Is there a way we push a static content to kadalu.github.io repo, say, `kadalu.io/repo/kadalu/latest`, which would be updated from the release script and we can have release version always valid in docs by giving curl syntax with this link in release variable.

**Comment by aravindavk** [comment]
We can copy to `gh-pages` of this repo once released. If we copy `kubectl-kadalu` to root dir of `gh-pages` branch then it will be available as https://kadalu.io/kadalu/kubectl-kadalu

**Comment by aravindavk** [comment]
> We can copy to `gh-pages` of this repo once released. If we copy `kubectl-kadalu` to root dir of `gh-pages` branch then it will be available as https://kadalu.io/kadalu/kubectl-kadalu

Like this https://github.com/kadalu/docs/blob/master/.github/workflows/on-pr-merge.yml#L28-L33

**Comment by amarts** [comment]
sorry, earlier was using phone to type, so couldn't explain in detail. 

What I was thinking was something like below:

```
curl -LO https://github.com/kadalu/kadalu/releases/download/$(curl -L -s https://kadalu.io/releases/kadalu/latest.txt)/kubectl-kadalu
```

And in release scripts, we just update this text file and commit to repo, so the automatic build would be triggered on that repo too).

**Comment by amarts** [comment]
Ok, for now, lets get this with changing the part  where it says 0.7.7 to 0.8.0 ?? (here and also in quick-start.md?)

**Comment by aravindavk** [comment]
> Ok, for now, lets get this with changing the part where it says 0.7.7 to 0.8.0 ?? (here and also in quick-start.md?)

Ack. Short URL may look good in website. Like

```
curl -LO https://dl.kadalu.io/latest/kubectl-kadalu
```

That may need little work to set it up. I will change it to 0.8.0 in both the places

**Comment by amarts** [comment]
It is ok to have a curl command inside of a another curl... Reason, we can use the similar method for moana, glusterfs etc from kadalu later... So documents can all look uniform. Just a thought.

**Review by amarts — APPROVED** [review]

**Pull request merged**
