### PR TITLE
Upload `kubectl-kadalu` binary to release page

### PR DESCRIPTION
**Pull request by aravindavk**
Updates: #255
Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.io>

### CODE REVIEW

**Comment by aravindavk** [comment]
Not sure how to test this

**Review by amarts — APPROVED** [review]
Should we add prepare-release also as part of this, which generates the operator files?

**Comment by amarts** [comment]
> Not sure how to test this

We can make a alpha_release call it 0.7.2alpha

**Comment by aravindavk** [comment]
> Should we add prepare-release also as part of this, which generates the operator files?

Ack. `KADALU_VERSION=${VERSION} make prepare-release-manifests` and copy all manifest files with built version.

**Comment by aravindavk** [comment]
Currently copying all `yaml` files from `manifests` directory. Couldn't found a way to copy files of specific version. Looks like need to make changes to `Makefile` to generate new manifest files to separate directory.

**Review by amarts — APPROVED** [review]

**Pull request merged**
