### PR TITLE
Action to push the image to docker automatically

### PR DESCRIPTION
**Pull request by amarts**

### CODE REVIEW

**Comment by amarts** [comment]
Note, this needs secrets to be set. Mostly, also needs pypi credentials passed to the command.

**Comment by amarts** [comment]
Should we make a 0.5.1 and test after merging this?

**Comment by amarts** [comment]
Note that we need to set the secrets in repo after merging this.

**Review by aravindavk — APPROVED** [review]
Looks Good

**Comment by aravindavk** [comment]
> Should we make a 0.5.1 and test after merging this?

👍

**Comment by amarts** [comment]
Yes, I am in favor of testing it.

**Comment by amarts** [comment]
And surprisingly the tests are all green, but it didn't update the status. Not sure what happened.

**Pull request merged**
