### PR TITLE
change glusterfs version to 7.x

### LINKED ISSUE #38: release v0.2 with glusterfs-7.0
GlusterFS 7.0 is in RC state now. Once the release is out, it would be good to make a release.

Also, it would be great to have a release with glusterfs-7.0 available to kadalu users.

### PR DESCRIPTION
**Pull request by amarts**
Fixes: #38

### CODE REVIEW

**Comment by amarts** [comment]
This is to test if the issue is with fedora:31 or glusterfs_7.x. (from #128 )

**Comment by amarts** [comment]
Considering this is running fine, looks like there is some issue with fedora:31 and loopback devices as bind mount. Good thing is, we can still upgrade to glusterfs-7.x series.

**Comment by amarts** [comment]
So a question, @sac @aravindavk @sankarshanmukhopadhyay. Should we use 7.x series? I am in favor.

**Review by aravindavk — APPROVED** [review]

**Review by sac — APPROVED** [review]

**Comment by sac** [comment]
7.x is good.

**Pull request merged**
