### PR TITLE
remove namespace from CRD

### LINKED ISSUE #2739: Kustomize controller in status not ready with Kadalu resources
### Describe the bug

We deployed [Kadalu](https://github.com/kadalu/kadalu) with flux to provide local storage for our cluster.s  The manifests used:
[kadalu release](https://github.com/kadalu/kadalu/releases)

*  csi-nodeplugin-rke.yaml 
* kadalu-operator-rke.yaml
* kadalu-gluster-pool.yaml:

```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: kadula-pool-1
spec:
  type: Replica3
  storage:
    - node: node1
      device: /dev/vg00/kadalu
    - node: node2
      device: /dev/vg00/kadalu
    - node: node3
      device: /dev/vg00/kadalu
```
* kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kadalu-operator-rke.yaml
  - csi-nodeplugin-rke.yaml
  - kadalu-gluster-pool.yaml
```
Flux installs the resources successfully in the cluster but the kustomization fails to become ready:

```
timeout waiting for: [CustomResourceDefinition/kadalu/kadalustorages.kadalu-operator.storage status: 'Unknown']
```
Using `kubectl apply -f *`  and `kustomize build . | kubectl apply -f - ` works without an issue

### Steps to reproduce

1. Deploy the above kustomization with flux
2. Watch resources get deployed but the status remains not ready due to the error `timeout waiting for: [CustomResourceDefinition/kadalu/kadalustorages.kadalu-operator.storage status: 'Unknown']`

### Expected behavior

kustomization to become ready as `kustomize build. | kubectl apply -f -` works and manifests are applied into the cluster

### Screenshots and recordings

_No response_

### OS / Distro

Centos 7.9

### Flux version

flux: v0.30.2

### Flux check

```
► checking prerequisites
✗ Kubernetes version v1.19.4 does not match >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2@sha256:c4b53b8e5488d4fc660378c88d280b73b195578989f6a505004c94254ec32328
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.14.1
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.11.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.2@sha256:903ffae9ec09482741c23c5fe082c07303b91b03b07c1183cf6f23fe4d4af115
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.1@sha256:29772d806cb23b64f8c2c570695bc139e5f3f5ba2a0c15b939dbfd6062264a94
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.4@sha256:1c239989647559e52e5201583dce3a33e6a0f039349ddd793762324622a247ae
```

### Git provider

GitLab

### Container Registry provider

GitLab

### Additional context
```bash
kubectl get po -n kadalu
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-822sc   3/3     Running   0          4d11h
kadalu-csi-nodeplugin-8fbsd   3/3     Running   0          4d11h
kadalu-csi-nodeplugin-rnmcc   3/3     Running   0          4d11h
kadalu-csi-provisioner-0      5/5     Running   0          4d11h
operator-f46c58cd9-hm4l2      1/1     Running   0          4d11h
server-kadula-pool-1-0-0      1/1     Running   0          4d
server-kadula-pool-1-1-0      1/1     Running   0          4d
server-kadula-pool-1-2-0      1/1     Running   0          4d
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chuegel**
CRDs which are namespace scoped should not have metadata.namespace defined. See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition. 
In our particular case, this will prevent Flux to reconcile the kustomization:
```bash
timeout waiting for: [CustomResourceDefinition/kadalu/kadalustorages.kadalu-operator.storage status: 'Unknown']
```
**What this PR does / why we need it**:
It removes the namespace from the CRD as described in the [CRD definition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition)

**Which issue(s) this PR fixes**:
Fixes: https://github.com/fluxcd/flux2/issues/2739

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

### CODE REVIEW

**Comment by leelavg** [comment]
@chuegel thanks for the PR.

- Would you pls remove [this](https://github.com/kadalu/kadalu/blob/devel/templates/operator.yaml.j2#L73) line and run `make gen-requirements` for this PR?

**Comment by chuegel** [comment]
@leelavg I'm unable to run `make gen-requirements` 

```bash
Generating requirements file for all kadalu components and CI
pip-compile --extra=builder -o requirements/builder-requirements.txt --allow-unsafe
ERROR:pep517.envbuild:WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
ERROR:pep517.envbuild:You should consider upgrading via the '/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/bin/python3.10 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/Users/macuser/projects/third-party/brew/bin/pip-compile", line 33, in <module>
    sys.exit(load_entry_point('pip-tools==6.6.1', 'console_scripts', 'pip-compile')())
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/piptools/scripts/compile.py", line 408, in cli
    dist = meta.load(os.path.dirname(os.path.abspath(src_file)))
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/meta.py", line 71, in load
    path = Path(build_as_zip(builder))
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/meta.py", line 58, in build_as_zip
    builder(dest=out_dir)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/meta.py", line 53, in build
    _prep_meta(hooks, env, dest)
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/meta.py", line 28, in _prep_meta
    reqs = hooks.get_requires_for_build_wheel({})
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/wrappers.py", line 75, in quiet_subprocess_runner
    check_output(cmd, cwd=cwd, env=env, stderr=STDOUT)
  File "/Users/macuser/projects/third-party/brew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/macuser/projects/third-party/brew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/bin/python3.10', '/Users/macuser/projects/third-party/brew/Cellar/pip-tools/6.6.1/libexec/lib/python3.10/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/var/folders/b4/vf33841d4j1099xfhtn4tvk00000gn/T/tmpensgdumf']' returned non-zero exit status 1.
make: *** [gen-requirements] Error 1
```
Any advice? Thanks

**Comment by leelavg** [comment]
Uh oh, sry it's `make gen-manifests` and pls install `jinja2` which is used for generating manifests.

Pls take a look at Makefile for more info. Thanks.

**Comment by chuegel** [comment]
Done, thank you

**Comment by leelavg** [comment]
- would you pls sign your commit and then I'll merge PR?

**Comment by chuegel** [comment]
Uhm the commits look signed to me?! Am I missing something?

**Comment by aravindavk** [comment]
> * would you pls sign your commit and then I'll merge PR?

Looks like some commits doesn't have signoff details. You can fix that while doing Squash and Merge.

**Comment by leelavg** [comment]
> You can fix that while doing Squash and Merge.
- ack


@chuegel 
- it seems that you cherry-picked some commits by mistake, could you pls rebase on devel branch and force push your PR, i'll take care of signing if it doesn't appear during squash-merge
- pardon the inconvenience

**Review by vatsa287 — APPROVED** [review]

**Pull request merged**
