### PR TITLE
Updated Read me to contains commands to allow kadalu to run on OCP. 

### PR DESCRIPTION
**Pull request by ChrisPhillips-cminion**
This was tested on OCP 4.8

Signed-off-by: Chris Phillips <chris.phillips@uk.ibm.com>

### CODE REVIEW

**Comment by leelavg** [comment]
@ChrisPhillips-cminion 

- thanks for the PR!
- could you pls cross check the manifest that you installed. It should be suffixed with openshift in the releases page
- SCCs are already part of the manifest https://github.com/kadalu/kadalu/blob/24a634/manifests/kadalu-operator-openshift.yaml#L34-L63

**Comment by amarts** [comment]
Can we merge it and then look into the points updated by @leelavg as a followup?

**Comment by leelavg** [comment]
- No, we better wait for the response
- What I was thinking which lead to this scenario is, user might have installed Kadalu via kadalu-cli and it didn't picked up correct manifest for the platform (let's say, cli picked up generic manifest in place of openshift)
- User tried to add SCCs and kadalu started working
- We need to make changes to CLI to pick-up correct manifest if it's not doing it currently

**Comment by hunter86bg** [comment]
@ChrisPhillips-cminion ,
why would you need to add those on Openshift ?
I'm running Kadalu on OKD4.10 and I never needed to set those .

**Comment by leelavg** [comment]
- Based on above comment and also we do have separate manifests for Openshift Deployments, closing this PR
- Pls re-raise if required

**Pull request closed without merging**
