### PR TITLE
operator: fixed the pylint error in main.py

### LINKED ISSUE #453: pylint: error seen on ubuntu20.04 images
```
************* Module main
operator/main.py:592:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
make: *** [Makefile:77: pylint] Error 8
```

This happened after CI shifted to ubuntu-latest (20.04).

### PR DESCRIPTION
**Pull request by manav-7**
There was a pylint error for inconsistent-return statements, now fixed.
Fixes: https://github.com/kadalu/kadalu/issues/453

### CODE REVIEW

**Comment by aravindavk** [comment]
Two more similar issues to fix.

```
************* Module storage_add
14
storage_add.py:136:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
15
************* Module storage_remove
16
storage_remove.py:54:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
```

Once you fix the issue locally, run the following

```
git add .
git commit -s --amend
# Update the commit message and add Fixes like below
Fixes: #453
git push origin refix-operator -f
```

**Comment by amarts** [comment]
Good pylint errors are now gone!

Again, DCO errors come because `-s` is not used in commits. While `-s` is not a requirement when working in a company or personal projects, it is required in an opensource project so you give consent to contributor guide, and license of the project.

[Recording it here for people wondering why DCO is critical].

**Review by amarts — APPROVED** [review]

**Comment by amarts** [comment]
Looks like the `--amend` option was done on previous commits :-)

Suggestion! just do a reset to latest devel 

```
git branch i447; 
git checkout i447;
git reset --hard origin/devel; 
make your changes of adding return statements in all files; 
git commit -a -s; 
here add proper commit msg; git push to local branch to fix the issue;
```

**Comment by amarts** [comment]
anyways, if this run works fine, will make a merge. Dont push before next job :+1:

**Comment by manav-7** [comment]
No sir, I was making the changes on GitHub itself in
https://github.com/manav-7/kadalu and then running ammend on the terminal
so it was restarting

**Comment by manav-7** [comment]
Yes sir, I fixed the glitch.

**Pull request merged**
