### PR TITLE
Add Pod annotations to allow Prometheus scraping

### LINKED ISSUE #626: Add pod annotations on kadalu-csi statefulset to allow Prom scraping process
Hi. It could be useful to add pod annotations on `kadalu-csi-statefulset` to allow Prometheus to autmatically scrape metrics exported by `kadalu-csi-provisionner-0`. It would avoid having to configure Prometheus. Thanks.

```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kadalu-csi-provisioner
  namespace: {{ namespace }}
(...)
template:
    metadata:
      name: csi-provisioner
      namespace: {{ namespace }}
      labels:
        app.kubernetes.io/part-of: kadalu
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: kadalu-csi-provisioner
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
```

### PR DESCRIPTION
**Pull request by tili41**
Fixes: #626

Signed-off-by: Louis Charreau <louis.charreau@vadesecure.com>

### CODE REVIEW

**Review by leelavg — DISMISSED** [review]
LGTM

**Review by aravindavk — APPROVED** [review]

**Comment by leelavg** [comment]
@tili41 might be one of the gotchas in Yaml, can you please quote both 8000 and true?

However quoting port would be fine but ig quoting string irrespective of values `"true"` might be considered truthy 🤔?

**Comment by tili41** [comment]
> @tili41 might be one of the gotchas in Yaml, can you please quote both 8000 and true?
> 
> However quoting port would be fine but ig quoting string irrespective of values `"true"` might be considered truthy 🤔?

Yes spontaneously, I would not have put a quote for a boolean and an integer. Looking at other examples of Prometheus annotations, I think we can use double quotes.

**Review by leelavg — APPROVED** [review]
LGTM

**Pull request merged**
