### PR TITLE
Apply tolerations from CR on server and nodeplugin pods

### PR DESCRIPTION
**Pull request by leelavg**
- thoroughly tested and might fix many asks from users

Signed-off-by: Leela Venkaiah G <leelavg@thoughtexpo.com>

### CODE REVIEW

**Comment by leelavg** [comment]
- will be updating the metrics docs in another PR

**Review by amarts — APPROVED** [review]
LGTM. Would be good if @aravindavk also takes a look.

**Review by aravindavk — APPROVED** [review]

**Comment by fastlorenzo** [comment]
@leelavg this doesn't cover server pods as they are deployed using `StatefulSet` and not `DaemonSet`

**Comment by leelavg** [comment]
@fastlorenzo I don't think so, tested this before raising PR.

Many I know what's missing from https://github.com/kadalu/kadalu/blob/devel/templates/server.yaml.j2#L26-L36?

**Pull request merged**
